[tool.poetry]
name = "python-action-test"
version = "0.0.1"
description = "test repository for python-action"
authors = ["rcmdnk <rcmdnk@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
pytest-benchmark = "^4.0.0"

[tool.poetry.dev-dependencies]
pytest = "7.3.0"
pytest-cov = "4.0.0"
pytest-xdist = "3.2.1"
pre-commit = "2.21.0"
black = "22.12.0"

[tool.pytest.ini_options]
addopts = "-n auto --benchmark-disable --benchmark-sort=fullname --benchmark-name=short --ignore tests/test_fail.py"
testpaths = ["tests",]
