---
name: test

on:
  push:
    branches-ignore:
      - "coverage"
      - "renovate/**"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        id: dispatch
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          ref: ${{ github.ref }}
          github_token: ${{ github.token }}
          workflow_file_name: dispatch.yml
      - name: Write workflow url
        run: |
          echo Main job URL: ${{ steps.dispatch.outputs.workflow_url }} >> $GITHUB_STEP_SUMMARY
      - name: Check status
        run: |
          if [ "${{ steps.dispatch.outputs.conclusion }}" != "success" ];then
            exit 1
          fi
