---
name: test

on:
  push:
    branches-ignore:
      - "coverage"
      - "renovate/**"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: rcmdnk
          repo: python-action-test
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file_name: dispatch.yml
          propagate_failure: true
