---
name: test

on:
  push:
    branches-ignore:
      - "coverage"
      - "renovate/**"
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,macos-latest]
        python-version: ["3.10","3.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check is main
        id: is_main
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ] && [ "${{ matrix.os }}" = "ubuntu-latest" ] && [ "${{ matrix.python-version }}" = "3.10" ];then
            echo "flag=1" >> $GITHUB_OUTPUT
            echo "ABC=1" >> $GITHUB_OUTPUT
          else
            echo "flag=0" >> $GITHUB_OUTPUT
            echo "ABC=0" >> $GITHUB_OUTPUT
          fi
      - name: check is_main
        run: |
          echo ${{ steps.is_main.outputs.flag }}
          echo ${{ steps.is_main.outputs.ABC }}
      - name: check is_main if
        if: ${{ steps.is_main.outputs.flag == '1' }}
        run: echo hoge
      - name: check is_main if
        if: ${{ steps.is_main.outputs.flag == 1 }}
        run: echo hoge
      - name: check is_main if
        if: ${{ steps.is_main.outputs.flag == '1' && github.event_name != 'workflow_dispatch' && ! inputs.debug_enabled }}
        run: echo hoge
      - name: check is_main if
        if: ${{ steps.is_main.outputs.flag == '0' }}
        run: echo hoge
      - name: check is_main if
        if: ${{ steps.is_main.outputs.flag == 0 }}
        run: echo hoge
          #      - name: Cancel workflow
          #        if: ${{ steps.is_main.outputs.flag != '1' && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
          #        run: |
          #          curl -X POST \
          #            -H "Accept: application/vnd.github.v3+json" \
          #            -H "Authorization: token ${{ github.token }} " \
          #            https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/cancel
          #      - uses: rcmdnk/python-action@v1
          #        with:
          #          coverage-push: ${{ steps.is_main.outputs.flag }}
          #
          #      # Enable tmate debugging of manually-triggered workflows if the input option was provided
          #      - name: Setup tmate session
          #        uses: mxschmitt/action-tmate@v3
          #        if: ${{ steps.is_main.outputs.flag == '1' && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
